package com.kakeibo.util;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;

import com.kakeibo.KkbCategory;
import com.kakeibo.R;
import com.kakeibo.db.CategoriesDBAdapter;
import com.kakeibo.db.CategoriesLanDBAdapter;

import java.util.ArrayList;

public class PrepDB {
    public static void initCategoriesTable(SQLiteDatabase db) {
        ArrayList<KkbCategory> list = new ArrayList<>();

        KkbCategory income = new KkbCategory();
        income.code = 0;
        income.drawable = R.drawable.ic_category_income;
        income.location = 0;
        income.en = "INCOME";
        income.fr = "REV.";
        income.it = "ENTR.";
        income.jp = "収入";
        income.es = "INGRE";
        list.add(income);

        KkbCategory commodity = new KkbCategory();
        commodity.code = 1;
        commodity.drawable = R.drawable.ic_category_comm;
        commodity.location = 1;
        commodity.en = "COMM";
        commodity.fr = "ACHAT.";
        commodity.it = "ACQ.";
        commodity.jp = "生活雑貨";
        commodity.es = "MERCAN";
        list.add(commodity);

        KkbCategory meal = new KkbCategory();
        meal.code = 2;
        meal.drawable = R.drawable.ic_category_meal;
        meal.location = 2;
        meal.en = "MEAL";
        meal.fr = "ALIM.";
        meal.it = "ALIMEN.";
        meal.jp = "食事";
        meal.es = "COMIDA";
        list.add(meal);

        KkbCategory util = new KkbCategory();
        util.code = 3;
        util.drawable = R.drawable.ic_category_util;
        util.location = 3;
        util.en = "UTIL";
        util.fr = "FACTUR";
        util.it = "UTENZE";
        util.jp = "水道光熱";
        util.es = "UTIL";
        list.add(util);

        KkbCategory health = new KkbCategory();
        health.code = 4;
        health.drawable = R.drawable.ic_category_health;
        health.location = 4;
        health.en = "HEALTH";
        health.fr = "SANTÉ";
        health.it = "SALUTE";
        health.jp = "健康";
        health.es = "SALUD";
        list.add(health);

        KkbCategory edu = new KkbCategory();
        edu.code = 5;
        edu.drawable = R.drawable.ic_category_edu;
        edu.location = 5;
        edu.en = "EDU";
        edu.fr = "ETUDE";
        edu.it = "EDUCAZ";
        edu.jp = "教育";
        edu.es = "EDU";
        list.add(edu);

        KkbCategory cloth = new KkbCategory();
        cloth.code = 6;
        cloth.drawable = R.drawable.ic_category_cloth;
        cloth.location = 6;
        cloth.en = "CLOTH";
        cloth.fr = "VETEM.";
        cloth.it = "ABBIG.";
        cloth.jp = "衣服";
        cloth.es = "VESTID";
        list.add(cloth);

        KkbCategory trans = new KkbCategory();
        trans.code = 7;
        trans.drawable = R.drawable.ic_category_trans;
        trans.location = 7;
        trans.en = "TRANS";
        trans.fr = "TRANS.";
        trans.it = "TRASP.";
        trans.jp = "交通";
        trans.es = "TRANS";
        list.add(trans);

        KkbCategory ent = new KkbCategory();
        ent.code = 8;
        ent.drawable = R.drawable.ic_category_ent;
        ent.location = 12;
        ent.en = "ENT";
        ent.fr = "AMUSE.";
        ent.it = "DIVERT.";
        ent.jp = "娯楽";
        ent.es = "ENTRET";
        list.add(ent);

        KkbCategory ins = new KkbCategory();
        ins.code=9;
        ins.drawable = R.drawable.ic_category_ins;
        ins.location = 13;
        ins.en = "INS";
        ins.fr = "EPARG.";
        ins.it = "RISP.";
        ins.jp = "保険";
        ins.es = "SEGURO";
        list.add(ins);

        KkbCategory tax = new KkbCategory();
        tax.code=10;
        tax.drawable = R.drawable.ic_category_tax;
        tax.location = 14;
        tax.en = "TAX";
        tax.fr = "TAXE";
        tax.it = "TASSE";
        tax.jp = "税金";
        tax.es = "IMPUES";
        list.add(tax);

        KkbCategory other = new KkbCategory();
        other.code=11;
        other.drawable = R.drawable.ic_category_other;
        other.location = 15;
        other.en = "OTHER";
        other.fr = "AUTRE";
        other.it = "ALTRO";
        other.jp = "他";
        other.es = "OTROS";
        list.add(other);

        KkbCategory pet = new KkbCategory();
        pet.code = 12;
        pet.drawable = R.drawable.ic_category_pet;
        pet.location = 8;
        pet.en = "PET";
        pet.fr = "ANIM.C.";
        pet.it = "ANIM.D.";
        pet.jp = "ペット";
        pet.es = "MSCTA";
        list.add(pet);

        KkbCategory social = new KkbCategory();
        social.code = 13;
        social.drawable = R.drawable.ic_category_social;
        social.location = 9;
        social.en = "SOCIAL";
        social.fr = "SOCIAL";
        social.it = "SOCIAL";
        social.jp = "交際";
        social.es = "SOCIAL";
        list.add(social);

        KkbCategory cosme = new KkbCategory();
        cosme.code=14;
        cosme.drawable = R.drawable.ic_category_cosme;
        cosme.location = 10;
        cosme.en = "COSME";
        cosme.fr = "COSMÉ";
        cosme.it = "COSME";
        cosme.jp = "美容";
        cosme.es = "COSME";
        list.add(cosme);

        KkbCategory housing = new KkbCategory();
        housing.code = 15;
        housing.drawable = R.drawable.ic_category_housing;
        housing.location = 11;
        housing.en = "HOUSNG";
        housing.fr = "LOGMNT";
        housing.it = "ABITAT.";
        housing.jp = "居住";
        housing.es = "VVENDA";
        list.add(housing);

        for (KkbCategory category: list) {
            ContentValues values = new ContentValues();
            values.put(CategoriesDBAdapter.COL_CODE, category.getCode());
            values.put(CategoriesDBAdapter.COL_NAME, "");
            values.put(CategoriesDBAdapter.COL_COLOR, 0);
            values.put(CategoriesDBAdapter.COL_DRAWABLE, category.getDrawable());
            values.put(CategoriesDBAdapter.COL_LOCATION, category.getLocation());
            values.put(CategoriesDBAdapter.COL_SUB_CATEGORIES, 0);
            values.put(CategoriesDBAdapter.COL_DESC, "");
            values.put(CategoriesDBAdapter.COL_SAVED_DATE, "");
            db.insertOrThrow(CategoriesDBAdapter.TABLE_CATEGORY, null, values);

            ContentValues values2 = new ContentValues();
            values2.put(CategoriesLanDBAdapter.COL_CODE, category.getCode());
            values2.put(CategoriesLanDBAdapter.COL_NAME, "");
            values2.put(CategoriesLanDBAdapter.COL_EN, category.getEN());
            values2.put(CategoriesLanDBAdapter.COL_ES, category.getES());
            values2.put(CategoriesLanDBAdapter.COL_FR, category.getFR());
            values2.put(CategoriesLanDBAdapter.COL_IT, category.getIT());
            values2.put(CategoriesLanDBAdapter.COL_JA, category.getJA());
            values2.put(CategoriesLanDBAdapter.COL_SAVED_DATE, "");
            db.insertOrThrow(CategoriesLanDBAdapter.TABLE_CATEGORY_LAN, null, values2);
        }
    }

    public static void initCategoriesTableRevised(SQLiteDatabase db, int version) {
        ArrayList<KkbCategory> list = new ArrayList<>();

        KkbCategory income = new KkbCategory();
        income.code = 0;
        income.drawable = R.drawable.ic_category_income;
        income.location = 0;
        income.en = "INCOME";
        income.fr = "REV.";
        income.it = "ENTR.";
        income.jp = "収入";
        income.es = "INGRE";
        income.ar = "الإيرادات";
        income.hi = "आय";
        income.ind = "PENDAPATAN";
        income.ko = "수입";
        income.pl = "DOCHÓD";
        income.pt = "RENDA";
        income.ru = "доход";
        income.tr = "GELİR";
        income.zh_hans = "收入";
        income.zh_hant = "收入";
        list.add(income);

        KkbCategory commodity = new KkbCategory();
        commodity.code = 1;
        commodity.drawable = R.drawable.ic_category_comm;
        commodity.location = 1;
        commodity.en = "COMM";
        commodity.fr = "ACHAT.";
        commodity.it = "ACQ.";
        commodity.jp = "生活雑貨";
        commodity.es = "MERCAN";
        commodity.ar = "السلع";
        commodity.hi = "वस्तु";
        commodity.ind = "KOMODITI";
        commodity.ko = "상품";
        commodity.pl = "TOWAR";
        commodity.pt = "MERCADORIA";
        commodity.ru = "товар";
        commodity.tr = "EMTİA";
        commodity.zh_hans = "商品";
        commodity.zh_hant = "商品";
        list.add(commodity);

        KkbCategory meal = new KkbCategory();
        meal.code = 2;
        meal.drawable = R.drawable.ic_category_meal;
        meal.location = 2;
        meal.en = "MEAL";
        meal.fr = "ALIM.";
        meal.it = "ALIMEN.";
        meal.jp = "食事";
        meal.es = "COMIDA";
        meal.ar = "وجبة";
        meal.hi = "भोजन";
        meal.ind = "MAKAN";
        meal.ko = "식사";
        meal.pl = "POSIŁEK";
        meal.pt = "REFEIÇÃO";
        meal.ru = "еда";
        meal.tr = "YEMEK";
        meal.zh_hans = "膳食";
        meal.zh_hant = "膳食";
        list.add(meal);

        KkbCategory util = new KkbCategory();
        util.code = 3;
        util.drawable = R.drawable.ic_category_util;
        util.location = 3;
        util.en = "UTIL";
        util.fr = "FACTUR";
        util.it = "UTENZE";
        util.jp = "水道光熱";
        util.es = "UTIL";
        util.ar = "خدمة";
        util.hi = "उपयोगिता";
        util.ind = "UTIL";
        util.ko = "유용";
        util.pl = "UŻYTECZNOŚĆ";
        util.pt = "UTIL";
        util.ru = "Утилита";
        util.tr = "YARAR";
        util.zh_hans = "效用";
        util.zh_hant = "效用";
        list.add(util);

        KkbCategory health = new KkbCategory();
        health.code = 4;
        health.drawable = R.drawable.ic_category_health;
        health.location = 4;
        health.en = "HEALTH";
        health.fr = "SANTÉ";
        health.it = "SALUTE";
        health.jp = "健康";
        health.es = "SALUD";
        health.ar = "الصحة";
        health.hi = "स्वास्थ्य";
        health.ind = "KESEHATAN";
        health.ko = "건강";
        health.pl = "ZDROWIE";
        health.pt = "SAÚDE";
        health.ru = "Здоровье";
        health.tr = "SAĞLIK";
        health.zh_hans = "健康";
        health.zh_hant = "健康";
        list.add(health);

        KkbCategory edu = new KkbCategory();
        edu.code = 5;
        edu.drawable = R.drawable.ic_category_edu;
        edu.location = 5;
        edu.en = "EDU";
        edu.fr = "ETUDE";
        edu.it = "EDUCAZ";
        edu.jp = "教育";
        edu.es = "EDU";
        edu.ar = "التعليم";
        edu.hi = "शिक्षा";
        edu.ind = "PENDIDIKAN";
        edu.ko = "교육";
        edu.pl = "EDUKACJA";
        edu.pt = "EDUCAÇÃO";
        edu.ru = "образование";
        edu.tr = "EĞİTİM";
        edu.zh_hans = "教育";
        edu.zh_hant = "教育";
        list.add(edu);

        KkbCategory cloth = new KkbCategory();
        cloth.code = 6;
        cloth.drawable = R.drawable.ic_category_cloth;
        cloth.location = 6;
        cloth.en = "CLOTH";
        cloth.fr = "VETEM.";
        cloth.it = "ABBIG.";
        cloth.jp = "衣服";
        cloth.es = "VESTID";
        cloth.ar = "ملابس";
        cloth.hi = "कपड़ा";
        cloth.ind = "PAKAIAN";
        cloth.ko = "의류";
        cloth.pl = "ODZIEŻ";
        cloth.pt = "ROUPAS";
        cloth.ru = "Одежда";
        cloth.tr = "GİYİM";
        cloth.zh_hans = "衣服";
        cloth.zh_hant = "衣服";
        list.add(cloth);

        KkbCategory trans = new KkbCategory();
        trans.code = 7;
        trans.drawable = R.drawable.ic_category_trans;
        trans.location = 7;
        trans.en = "TRANS";
        trans.fr = "TRANS.";
        trans.it = "TRASP.";
        trans.jp = "交通";
        trans.es = "TRANS";
        trans.ar = "نقل";
        trans.hi = "परिवहन";
        trans.ind = "ANGKUTAN";
        trans.ko = "교통";
        trans.pl = "TRANSPORT";
        trans.pt = "TRANSPORTE";
        trans.ru = "Транспорт";
        trans.tr = "ULAŞIM";
        trans.zh_hans = "运输";
        trans.zh_hant = "運輸";
        list.add(trans);

        KkbCategory ent = new KkbCategory();
        ent.code = 8;
        ent.drawable = R.drawable.ic_category_ent;
        ent.location = 12;
        ent.en = "ENT";
        ent.fr = "AMUSE.";
        ent.it = "DIVERT.";
        ent.jp = "娯楽";
        ent.es = "ENTRET";
        ent.ar = "تسلية";
        ent.hi = "मनोरंजन";
        ent.ind = "HIBURAN";
        ent.ko = "환대";
        ent.pl = "ZABAWA";
        ent.pt = "ENTRETENIMENTO";
        ent.ru = "Развлечения";
        ent.tr = "EĞLENCE";
        ent.zh_hans = "娱乐";
        ent.zh_hant = "娛樂";
        list.add(ent);

        KkbCategory ins = new KkbCategory();
        ins.code=9;
        ins.drawable = R.drawable.ic_category_ins;
        ins.location = 13;
        ins.en = "INS";
        ins.fr = "EPARG.";
        ins.it = "RISP.";
        ins.jp = "保険";
        ins.es = "SEGURO";
        ins.ar = "تأمين";
        ins.hi = "बीमा";
        ins.ind = "ASURANSI";
        ins.ko = "보험";
        ins.pl = "UBEZPIECZENIE";
        ins.pt = "SEGURO";
        ins.ru = "страхование";
        ins.tr = "SİGORTA";
        ins.zh_hans = "保险";
        ins.zh_hant = "保險";
        list.add(ins);

        KkbCategory tax = new KkbCategory();
        tax.code=10;
        tax.drawable = R.drawable.ic_category_tax;
        tax.location = 14;
        tax.en = "TAX";
        tax.fr = "TAXE";
        tax.it = "TASSE";
        tax.jp = "税金";
        tax.es = "IMPUES";
        tax.ar = "ضريبة";
        tax.hi = "कर";
        tax.ind = "PAJAK";
        tax.ko = "세";
        tax.pl = "PODATEK";
        tax.pt = "IMPOSTO";
        tax.ru = "налог";
        tax.tr = "VERGİ";
        tax.zh_hans = "税";
        tax.zh_hant = "稅";
        list.add(tax);

        KkbCategory other = new KkbCategory();
        other.code=11;
        other.drawable = R.drawable.ic_category_other;
        other.location = 15;
        other.en = "OTHER";
        other.fr = "AUTRE";
        other.it = "ALTRO";
        other.jp = "他";
        other.es = "OTROS";
        other.ar = "آخر";
        other.hi = "अन्य";
        other.ind = "LAIN";
        other.ko = "다른";
        other.pl = "INNY";
        other.pt = "OUTRO";
        other.ru = "Другие";
        other.tr = "DİĞER";
        other.zh_hans = "其他";
        other.zh_hant = "其他";
        list.add(other);

        KkbCategory pet = new KkbCategory();
        pet.code = 12;
        pet.drawable = R.drawable.ic_category_pet;
        pet.location = 8;
        pet.en = "PET";
        pet.fr = "ANIM.C.";
        pet.it = "ANIM.D.";
        pet.jp = "ペット";
        pet.es = "MSCTA";
        pet.ar = "حيوان اليف";
        pet.hi = "पालतू";
        pet.ind = "MEMBELAI";
        pet.ko = "착한 애";
        pet.pl = "ZWIERZĘ DOMOWE";
        pet.pt = "ANIMAL";
        pet.ru = "домашнее животное";
        pet.tr = "EVCİL HAYVAN";
        pet.zh_hans = "宠物";
        pet.zh_hant = "寵物";
        list.add(pet);

        KkbCategory social = new KkbCategory();
        social.code = 13;
        social.drawable = R.drawable.ic_category_social;
        social.location = 9;
        social.en = "SOCIAL";
        social.fr = "SOCIAL";
        social.it = "SOCIAL";
        social.jp = "交際";
        social.es = "SOCIAL";
        social.ar = "اجتماعي";
        social.hi = "सामाजिक";
        social.ind = "SOSIAL";
        social.ko = "사회적인";
        social.pl = "SPOŁECZNY";
        social.pt = "SOCIAL";
        social.ru = "Социальное";
        social.tr = "SOSYAL";
        social.zh_hans = "社会的";
        social.zh_hant = "社會的";
        list.add(social);

        KkbCategory cosme = new KkbCategory();
        cosme.code=14;
        cosme.drawable = R.drawable.ic_category_cosme;
        cosme.location = 10;
        cosme.en = "COSME";
        cosme.fr = "COSMÉ";
        cosme.it = "COSME";
        cosme.jp = "美容";
        cosme.es = "COSME";
        cosme.ar = "كوزمي";
        cosme.hi = "अंगराग";
        cosme.ind = "COSME";
        cosme.ko = "화장품";
        cosme.pl = "COSME";
        cosme.pt = "COSME";
        cosme.ru = "Косме";
        cosme.tr = "COSME";
        cosme.zh_hans = "化妆品";
        cosme.zh_hant = "化妝品";
        list.add(cosme);

        KkbCategory housing = new KkbCategory();
        housing.code = 15;
        housing.drawable = R.drawable.ic_category_housing;
        housing.location = 11;
        housing.en = "HOUSNG";
        housing.fr = "LOGMNT";
        housing.it = "ABITAT.";
        housing.jp = "居住";
        housing.es = "VVENDA";
        housing.ar = "إسكان";
        housing.hi = "आवास";
        housing.ind = "PERUMAHAN";
        housing.ko = "주택";
        housing.pl = "MIESZKANIOWY";
        housing.pt = "HABITAÇÃO";
        housing.ru = "Корпус";
        housing.tr = "KONUT";
        housing.zh_hans = "住房";
        housing.zh_hant = "住房";
        list.add(housing);

        for (int i = 0; i < 16; i++) {
            ContentValues values = new ContentValues();
            values.put(CategoriesLanDBAdapter.COL_CODE, list.get(i).getCode());
            values.put(CategoriesLanDBAdapter.COL_NAME, "");
            values.put(CategoriesLanDBAdapter.COL_EN, list.get(i).getEN());
            values.put(CategoriesLanDBAdapter.COL_ES, list.get(i).getES());
            values.put(CategoriesLanDBAdapter.COL_FR, list.get(i).getFR());
            values.put(CategoriesLanDBAdapter.COL_IT, list.get(i).getIT());
            values.put(CategoriesLanDBAdapter.COL_JA, list.get(i).getJA());
            values.put(CategoriesLanDBAdapter.COL_AR, list.get(i).getAR());
            values.put(CategoriesLanDBAdapter.COL_HI, list.get(i).getHI());
            values.put(CategoriesLanDBAdapter.COL_IND, list.get(i).getIN());
            values.put(CategoriesLanDBAdapter.COL_KO, list.get(i).getKO());
            values.put(CategoriesLanDBAdapter.COL_PL, list.get(i).getPL());
            values.put(CategoriesLanDBAdapter.COL_PT, list.get(i).getPT());
            values.put(CategoriesLanDBAdapter.COL_RU, list.get(i).getRU());
            values.put(CategoriesLanDBAdapter.COL_TR, list.get(i).getTR());
            values.put(CategoriesLanDBAdapter.COL_ZH_Hans, list.get(i).getZH_Hans());
            values.put(CategoriesLanDBAdapter.COL_ZH_Hant, list.get(i).getZH_Hant());
            values.put(CategoriesLanDBAdapter.COL_SAVED_DATE, "DBversion:" + version);
            db.insertOrThrow(CategoriesLanDBAdapter.TABLE_CATEGORY_LAN, null, values);
        }
    }
}
